### ISSUE TITLE
Does not look for int ?

### ISSUE THREAD

**Issue by ignatandrei** [tparviainen/query-string-generator#174]
In the example from
https://ignatandrei.github.io/RSCG_Examples/v2/docs/QueryStringGenerator#example--source-csproj-source-files-

the class
```csharp
using QueryStringGenerator;
namespace DemoQuery;
[QueryString]
internal class Person
{
    public string FirstName { get; set; }=string.Empty;
    public int Age {  get; set; }
    public string LastName { get; set; } = string.Empty;

}

```
the Age propery is not serialized - see 

https://ignatandrei.github.io/RSCG_Examples/v2/docs/QueryStringGenerator#generated-files

Is this a default behaviour, to serialize only strings?

**Comment by tparviainen** [comment]
For value types the type must be nullable to be part of the generated query string. The reason for that is that when declaring a value type

```csharp
int Age1;
int Age2 = 0;
```

The question is that, should `Age1` be part of the generated query string or not? Both `Age1` and `Age2` have a value 0 which makes it difficult to determine from the value itself that should it be in the generated query string or not.

In order to know exactly what should be part of the generated query string the value type must be nullable because then the source generator knows whether there is a value or not.

```csharp
int? Age3;
int? Age4 = 0;
```

Now because the value types are nullable types the source generator knows that `Age3` must **not** be part of the query string because there is no value (it's value is null) and `Age4` must be part of the query string because `Age4` contains a value 0.

The query string generator supports reference types and nullable value types and the generated query string contains the key-value-pairs only for those properties that have a value.
